### ISSUE TITLE
Feature Request: Provide Grafana dashboard

### ISSUE THREAD

**Issue by USSX-Hares** [celestialorb/factorio-prometheus-exporter#10]
It would be nice if this mod would also provide a Grafana dashboard with the exposed metrics.

**Comment by celestialorb** [comment]
I hear you, though Grafana dashboards can be pretty opinionated. For example I have one up geared around displaying early game resource production/consumption. In addition to that, the configuration of the Grafana dashboard may depend on the specific infrastructure setup of the Prometheus instance (as that is left up the user).

I wouldn't mind writing a couple of Grafana dashboard templates that could serve as starting points but personally I'd put them into a different repository.

**Comment by celestialorb** [comment]
Closing issue as stale.
