### ISSUE TITLE
Version bump for Space Age

### ISSUE THREAD

**Issue by ZCK12** [celestialorb/factorio-prometheus-exporter#11]
Space Age changed the Factorio version to 2.0 and made this mod incompatible. 
Can we please get a version bump? <3

**Comment by celestialorb** [comment]
I'd love to ensure it's compatible with Factorio 2! I'll see if I can get everything setup and make it compatible today.

**Comment by celestialorb** [comment]
> Space Age changed the Factorio version to 2.0 and made this mod incompatible. 
> Can we please get a version bump? <3 

I'd love to ensure it's compatible with Factorio 2! I'll see if I can get everything setup and make it compatible today.
